SELECT * FROM EMPLOYEES WITH(NOLOCK) 
ORDER BY EMPID DESC


--FIND THE 3RD HIGHEST SALARY IN THE WHOLE COMPANY WITHOUT USING TOP. SHOW SALARY ONLY.
WITH CTE AS 
(
	SELECT *,
	DENSE_RANK() OVER(ORDER BY SALARY DESC) RK
	FROM EMPLOYEES WITH(NOLOCK)
)
SELECT FNAME, LNAME, JOB_TITLE, DEPARTMENT, SALARY, CITY FROM CTE
WHERE RK = 3


--WHICH DEPARTMENT HIRED THE MOST PEOPLE IN LAST 2 YEARS (2024 + 2025)?
SELECT TOP 1 DEPARTMENT, COUNT(EMPID) AS TOTALEMP  FROM EMPLOYEES WITH(NOLOCK)
WHERE YEAR(HIRE_DATE) IN (2024, 2025)
GROUP BY DEPARTMENT
ORDER BY TOTALEMP DESC


--FIND EMPLOYEES WHO HAVE SAME FNAME BUT WORK IN DIFFERENT CITIES.
SELECT   E1.FNAME,E2.FNAME, E1.EMPID, E2.EMPID, E1.CITY  FROM EMPLOYEES E1 WITH(NOLOCK)
JOIN EMPLOYEES E2 ON E1.FNAME = E2.FNAME
AND E1.CITY <> E2.CITY 
AND E1.EMPID < E2.EMPID


--FOR EACH DEPARTMENT, ORDER EMPLOYEES BY SALARY DESC AND SHOW HOW MUCH LESS THE NEXT EMPLOYEE EARNS COMPARED TO PREVIOUS ONE.
WITH CTE AS 
(
	SELECT FNAME, DEPARTMENT, SALARY,   
	LAG(SALARY) OVER(PARTITION BY DEPARTMENT ORDER BY SALARY ASC) AS PREVIOUS_SALARY
	FROM EMPLOYEES WITH(NOLOCK)
)
SELECT FNAME, DEPARTMENT , SALARY, 
PREVIOUS_SALARY - SALARY AS SALARY_DIFF
FROM CTE


--FOR EACH DEPARTMENT, ORDER EMPLOYEES BY SALARY DESC AND SHOW HOW MUCH LESS THE NEXT EMPLOYEE EARNS COMPARED TO PREVIOUS ONE.
WITH CTE AS 
(
	SELECT FNAME, DEPARTMENT, SALARY,   
	LEAD(SALARY) OVER(PARTITION BY DEPARTMENT ORDER BY SALARY ASC) AS PREVIOUS_SALARY
	FROM EMPLOYEES WITH(NOLOCK)
)
SELECT FNAME, DEPARTMENT , SALARY, 
PREVIOUS_SALARY - SALARY AS SALARY_DIFF
FROM CTE


--WRITE A QUERY TO FIND DUPLICATE EMAILS AND ANOTHER QUERY TO DELETE THE DUPLICATE KEEPING ONLY 1 WITH LOWEST EMPID.
SELECT EMAIL, COUNT(EMAIL) AS TOTAL FROM EMPLOYEES WITH(NOLOCK)
GROUP BY EMAIL
HAVING COUNT(EMAIL) > 1